### ISSUE TITLE
离线解析

### ISSUE THREAD

**Issue by spihiker** [liuhr/my2sql#7]
大佬，离线解析啥时候发版？期待！

**Comment by liuhr** [comment]
最近一段时间会尽快支持。

**Comment by oraclescjx** [comment]
离线模式为什么还需要相关MySQL服务器配置？ -user root -password xxxx -host 127.0.0.1   -port 3306

**Comment by liuhr** [comment]
当前还需要连接到数据获得表结构信息，才能构建sql语句。
















在 2021-09-10 20:34:13，"oraclescjx" ***@***.***> 写道：

离线模式为什么还需要相关MySQL服务器配置？ -user root -password xxxx -host 127.0.0.1 -port 3306

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
